config/routes.rb
ListenLoop::Application.routes.draw do

  resources :presentations

  get 'my_presentations' => 'presentations#my_presentation'

  resources :feedbacks

  devise_for :employees,controllers: {sessions: "sessions"}
  devise_scope :employee do
    root to: "devise/sessions#new"
  end

  get '/dashboard' => 'employees#dashboard'

  resources :employees
  get '/home'=> 'pages#home'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :feedbacks
  has_many :presentations
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :employee
  has_attached_file :logo
  validates_attachment_content_type :logo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/presentation.rb
class Presentation < ActiveRecord::Base

  belongs_to :employee
  has_many :feedbacks , through: :presentation_feedbacks
  has_many :presentation_feedbacks
end

app/models/presentation_feedback.rb
class PresentationFeedback < ActiveRecord::Base
  belongs_to :presentation
  belongs_to :feedback

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def is_admin?
    redirect_to dashboard_path unless current_employee.admin? if session[:employee_id].present?
  end

  def after_sign_in_path_for(resource)
      request.url + "dashboard"
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  #before_filter :authenticate_employee!, expect: [:new]

  def dashboard

  end

  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
      if @employee.save
        redirect_to  employees_path  , notice:'Employee created'
      else
        render 'new'
      end
  end

  def edit

  end

  def update
    if @employee.update(employee_params)
      redirect_to employees_path
    else
      render action: 'edit'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:email, :password, :password_confirmation, :isadmin)
  end


end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @employer = current_employee
    @feedback = @employer.feedbacks.build(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render action: 'show', status: :created, location: @feedback }
      else
        format.html { render action: 'new' }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:employee_id, :client_name, :message, :location, :logo_attributes,:logo)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home

end


end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :set_presentation, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_employee!, only: [:index,:new,:create,:destroy,:edit,:my_presentation]
  layout "presentation", only: [:show]




  # GET /presentations
  # GET /presentations.json
  def index
    @presentations = Presentation.all.where(:publish => true)
  end

  # GET /presentations/1
  # GET /presentations/1.json
  def show
    @presentation = Presentation.find(params[:id])
    @feedbacks = @presentation.feedbacks


  end

  # GET /presentations/new
  def new
    @presentation = Presentation.new
  end

  # GET /presentations/1/edit
  def edit
  end

  # POST /presentations
  # POST /presentations.json
  def create
    @employee = current_employee
    @presentation = @employee.presentations.build(presentation_params)

    respond_to do |format|
      if @presentation.save
        format.html { redirect_to @presentation, notice: 'Presentation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @presentation }
      else
        format.html { render action: 'new' }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  def my_presentation
    @employee = current_employee
    @presentations = current_employee.presentations

  end

  # PATCH/PUT /presentations/1
  # PATCH/PUT /presentations/1.json
  def update
    params[:presentation][:feedback_ids] ||= []
    respond_to do |format|
      if @presentation.update(presentation_params)
        format.html { redirect_to @presentation, notice: 'Presentation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1
  # DELETE /presentations/1.json
  def destroy
    @presentation.destroy
    respond_to do |format|
      format.html { redirect_to presentations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presentation_params
      params.require(:presentation).permit(:title, :employer_id, :publish,:feedback_ids=> [])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController




  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)
    session[:employee_id] = resource.id

      respond_to do |format|
        if employee_signed_in?
          format.html { redirect_to dashboard_path, notice: 'You Signed In' }

        else
          format.html { render action: 'new',alert: "Invalid email/password combination" }
          format.json { render json: @employee.errors, status: :unprocessable_entity }
        end
      end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def data_slide_index
    return 0

  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/employees/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for @employee do |f| %>

        <% if @employee.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this schedule from being saved:</h2>

              <ul>
                <% @employee.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>



        <%= f.label :email %>
        <%= f.text_field :email %><br/>

        <%= f.label :password %>
        <%= f.password_field :password %><br/>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.label :isadmin, "Admin" %>
        <%= f.check_box :isadmin %>
        <br/>
        <%= f.submit "Add new employee", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/employees/dashboard.html.erb
this is dashboard

app/views/employees/edit.html.erb
<h1> Edit Employee</h1>

<%= render 'form' %>

<% link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<br/>
<br/>
<h1>All Employee</h1>
<%= link_to 'ADD New Employee', new_employee_path,:class=>"btn" %>

<div class = "hero-unit">
  <table>
    <thead><td><b>Email</b></td></thead>

    <tbody>
    <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.email  %></td>
          <td><%= link_to 'change Password', edit_employee_url(employee) ,:class=>"btn"%></td>
          <td><%= link_to 'delete',:class=>"btn" %>
        </tr>
        </tbody>
    <% end %>

    </table>


</div>

app/views/employees/new.html.erb
<h1>Add New Emplyee</h1>
<%= render 'form' %>

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :client_name %><br>
    <%= f.text_field :client_name %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
    <div class="field">
      <%= f.label :logo  %>
      <%= f.file_field :logo, class: "image_file" %>
    </div>
  <div class="actions">
    <%= f.submit "Add new feedback", class: "btn btn-large btn-primary"%>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<h1>Listing feedbacks</h1>

<%= link_to 'ADD New Feedback', new_feedback_path,:class=>"btn" %>

<div class = "hero-unit">
<table  >
  <thead>
    <tr>
      <th>Employee</th>
      <th>Client name</th>
      <th>Message</th>
      <th>Location</th>
      <th>Logo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.employee.email %></td>
        <td><%= feedback.client_name %></td>
        <td><%= feedback.message %></td>
        <td><%= feedback.location %></td>
        <td><%= feedback.logo_file_name %></td>
        <td><%= link_to 'Show', feedback, :class=>"btn"%></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback),:class=>"btn" %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } ,:class=>"btn"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/feedbacks/new.html.erb
<h1>New feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @feedback.employee.email %>
</p>

<p>
  <strong>Client name:</strong>
  <%= @feedback.client_name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @feedback.message %>
</p>

<p>
  <strong>Location:</strong>
  <%= @feedback.location %>
</p>

<p>
  <strong>Logo:</strong>
  <%= image_tag @feedback.logo.url, :size => "100x100" %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ListenLoop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
   
</head>
<body>

<div id = "main">
<% if employee_signed_in? %>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <ul class="nav">
          <li> <%= link_to 'Logout',destroy_employee_session_path,method: "delete"   %></li>
          <li><%= link_to 'Dashboard',dashboard_path  %></li>
          <li><%= link_to 'My Presentations' ,my_presentations_path  %></li>
          <li><%= link_to 'All Presentation',presentations_path %></li>
          <li><%= link_to 'All Feedbacks', feedbacks_path %>
          <% if current_employee.isadmin? %>
            <li><%= link_to 'All Employee' , employees_path %></li>
            <li><%=    %></li>
           <% end %>
           </ul>
        </div>
     </div>
   </div>

<%else%>
              <div class="navbar">
                <div class="navbar-inner">
                  <div class="container">
                    <ul class="nav">

                     </ul>
                   </div>
                 </div>
               </div>
           <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">

    <%= yield %>

  </div>
</div>

</body>
</html>

app/views/layouts/presentation.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ListenLoop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div id = "main">



    <%= yield %>


</div>

</body>
</html>

app/views/presentations/_form.html.erb
<%= form_for(@presentation) do |f| %>
  <% if @presentation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@presentation.errors.count, "error") %> prohibited this presentation from being saved:</h2>
      <ul>
      <% @presentation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <h4> Select feedback you want to include in the presentation</h4>
    <div class = "field">
      <% Feedback.all.each do |feedback| %>

          <%= check_box_tag 'presentation[feedback_ids][]' , feedback.id, @presentation.feedbacks.include?(feedback) %> &nbsp;<%= feedback.client_name  %><br/>

      <% end %>
<br/>
  <div class="field">
    <%= f.label :publish %>
    <%= f.check_box :publish %>
  </div>
  <div class="actions">
    <%= f.submit"Add new presentation" , class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/presentations/edit.html.erb
<h1>Editing presentation</h1>

<%= render 'form' %>

<%= link_to 'Show', @presentation %> |
<%= link_to 'Back', presentations_path %>

app/views/presentations/index.html.erb
<h1>All presentations</h1>
<%= link_to 'New Presentation', new_presentation_path,:class=>"btn" %>
<div class = "hero-unit">
  <table>
    <thead>
    <tr>
      <th>Title</th>
      <th>Employer</th>
      <th>Publish</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @presentations.each do |presentation| %>
        <tr>
          <td><%= presentation.title %></td>
          <td><%= presentation.employee.email %></td>
          <td><%= presentation.publish %></td>
          <td><%= link_to 'Show', presentation ,:class=>"btn"%></td>
          <td><%= link_to 'Edit', edit_presentation_path(presentation),:class=>"btn" %></td>
          <td><%= link_to 'Destroy', presentation, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn" %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>
</div>

app/views/presentations/my_presentation.html.erb
<h1>My presentations</h1>
<%= link_to 'New Presentation', new_presentation_path,:class=>"btn" %>
<div class = "hero-unit">
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Employer</th>
    <th>Publish</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @presentations.each do |presentation| %>
      <tr>
        <td><%= presentation.title %></td>
        <td><%= presentation.employee.email %></td>
        <td><%= presentation.publish %></td>
        <td><%= link_to 'Show', presentation ,:class=>"btn"%></td>
        <td><%= link_to 'Edit', edit_presentation_path(presentation),:class=>"btn" %></td>
        <td><%= link_to 'Destroy', presentation, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn" %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
</div>

app/views/presentations/new.html.erb
<h1>New presentation</h1>

<%= render 'form' %>

<%= link_to 'Back', presentations_path %>

app/views/presentations/show.html.erb
<!--------------header--------------->
<div class="jumbotron header_bar" align="center">
  <div class="container">
    <h1></h1>
  </div>
</div>
<div class="jumbotron" align="center">
  <div>
    <h1>

       <%= image_tag("testimonial.jpg",:size=>"1500x1000") %>
    </h1>
  </div>
</div>
<!--------------/header--------------->
<div class="jumbotron socialbar">
  <div class="container">
    <div class="row">
      <div class="col-md-6 social">
        <ul>

          <li><%= image_tag("fb.png" ,:size => "30x30")%></li>
          <li><%= image_tag("twitter.png" ,:size => "30x30")%></li>
          <li><%= image_tag("blog.png" ,:size => "30x30")%></li>

        </ul>
      </div>
    </div>
  </div>
</div>
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <h1 class="testi_h1"><%= @presentation.title%></h1>
        <div class="col-md-12">
          <ul class="bxslider">
            <% @feedbacks.each do |feedback| %>
            <li>
              <div class="people_img"><%= image_tag( feedback.logo.url ,:size => "200x200")%></div>
              <div class="people_talk"><p><%= image_tag("icon1.png", :width => 30, :height => 30)%>&nbsp;&nbsp;&nbsp; <%= feedback.message %> <%= image_tag("icon2.png", :width => 30, :height => 30 ,:class =>"icon2")%> </p>
                <h2><%= feedback.client_name %></h2>
              </div>
            </li>

            <% end %>

          </ul>


          <div id="bx-pager" style="text-align:center;">
            <% @feedbacks.each_with_index do |feedback,index| %>
            <a data-slide-index=<%= index %> href=""> <%= image_tag (feedback.logo.url) %></a>

          <% end %>
          </div>

        </div>
        <div class="col-md-12">
         <h1 class="testi_h1 client_speak">Clients Speaks</h1>
          <div class="col-md-6"  style="margin-top: 50px;">
          <iframe width="100%" height="215" src="http://www.youtube.com/embed/g4St8hx08S8" frameborder="0" allowfullscreen></iframe>
        </div>
        <div class="col-md-6"  style="margin-top: 50px;">
          <iframe width="100%" height="215" src="http://www.youtube.com/embed/ZB9l5cVbGek" frameborder="0" allowfullscreen></iframe>
        </div>
      </div>

    </div>
    <div class="col-md-3 sidebar">
      <h2 class="about_h2">
        About Us
      </h2>
      <p class="about_p">
        AboutUs.org started out as a wiki Internet domain directory. It listed websites along with information about their content. As a wiki, AboutUs allows Internet users to add entries or modify information. AboutUs.org has since become a wiki for more than just websites. The site now allows pages to be created for people, places, and almost anything else
      <p>
      <h2 class="about_h2">
        Contact Now
      </h2>
      <p class="about_p">
        <strong>Midwest Operations</strong><br/>
        <i>395 S. Glen Ellyn Road</i><br/>
        <i>Bloomingdale, IL 60108</i><br/>
        <i>Telephone: 888-669-3663</i><br/>
        <br/>
        <%= mail_to "me@domain.com", image_tag("e-mail icon.jpg", :size=>"100x100" )%>
         <p>
      <h2 class="about_h2">
        Our Products
      </h2>
      <p class="about_p">
        <%= link_to 'Content Management' ,:class => 'product_link' %><br/>
        <%= link_to 'Headend Systems Integrated ' ,:class => 'product_link' %><br/>
        <%= link_to 'Receiver Decoders Mediaroom ' ,:class => 'product_link' %><br/>
        <%= link_to 'Platforms Media Delivery Network ' ,:class => 'product_link' %><br/>
        <%= link_to 'Platforms Modulators Multiscreen ' ,:class => 'product_link' %><br/>
        <%= link_to 'Clients Multiscreen Core Platforms ' ,:class => 'product_link' %><br/>
        <%= link_to 'Stream Processors Video ' ,:class => 'product_link' %><br/>
        <%= link_to 'Processing Control  ' ,:class => 'product_link' %><br/>
        <%= link_to 'Management Video Processors ' ,:class => 'product_link' %><br/>
      <p>
    </div>
  </div>
  </div>
  </div>